SELECT * FROM restaurant_reservation.view_customers;
SELECT * FROM restaurant_reservation.view_items;
SELECT * FROM restaurant_reservation.view_locations;
SELECT * FROM restaurant_reservation.view_orders;
SELECT * FROM restaurant_reservation.view_payments;
SELECT * FROM restaurant_reservation.view_promotions;
SELECT * FROM restaurant_reservation.view_reservations;
SELECT * FROM restaurant_reservation.view_tables;
SELECT * FROM restaurant_reservation.view_workers;